#!/usr/bin/env php
<?php

$config = require(__DIR__ . '/config/console.php');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

exit((new app\models\ApplicationConsole($config))->run());
